### ISSUE TITLE
Implement the project grouping on the dashboard (including Discourse)

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-metrics-org#99] opened 2017-06-01 11:13 UTC
Implement the [project grouping](https://docs.google.com/spreadsheets/d/1xFrt9JZkZ6m8peasYaRfPO5kC1JDo-vDJJuYfMwcGqM/edit#gid=994958943) on the dashboard (including Discourse)

**Comment by jgbarah** [comment] 2017-06-07 11:33
Project grouping, except for Reps, is complete in mozilla-test. I guess you haave credentials to check those in the corresponding Kibana (or @alpgarcia is sending them to you shortly). Number could be checked in that Kibana (and some drill down as well).

For now, not updating the dashboard with this data, but will try to do after other stuff is done.

**Comment by nukeador** [comment] 2017-06-22 21:09
Hi,

Let's make this happen also on production :-)

Cheers.

**Comment by nukeador** [comment] 2017-07-05 11:38
@sanacl please, let's make sure this issue is updated. Thanks!

**Comment by jgbarah** [comment] 2017-07-10 22:12
We're working on this, since for the test ES we had specific software that read from the spreadsheet and updated directly the indexes. But for the production ES we need to include that in the incremental retrieval process, and use the projects.json file we use in production instead of the spreadsheet. We already have a first version of the projects.json, we need to start deploying it, one data source at a time.

**Comment by nukeador** [comment] 2017-07-14 10:10
Thanks, please let us know when this is done.

**Comment by nukeador** [comment] 2017-07-25 13:35
Hi, can we get an update here? We would like to understand status and ETA.

Thanks!

**Comment by sanacl** [comment] 2017-07-27 10:51
New project grouping will be ready by Wednesday EOB for the following data sources: Git, Github and Mailing Lists. This will unblock the next phase of the project as @dicortazar confirmed.

The rest of the data sources need to be supported first. I guess this is done during Aug/September but I can't commit with a date for this.

**Comment by sanacl** [comment] 2017-07-28 10:47
Done for Git and Github.

**Comment by sanacl** [comment] 2017-08-02 08:16
Done for:
* Git + Github
* Mailing lists.

To be done:
* Bugzilla
* Discourse

Do we need it for the following data sources??:
* Mediawiki
* Remo
* Twitter

**Comment by hmitsch** [comment] 2017-08-02 10:13
* Twitter: Can be removed because our license expired.
* Remo: No grouping required
* MediaWiki: No grouping required

**Comment by hmitsch** [comment] 2017-08-18 20:11
Looks like the list of **To be done** still needs to be added:
* GitHub Issues Timing

**Comment by nukeador** [comment] 2017-08-21 12:34
Hi,

I think we need Remo groping in order to understand under which project people are reporting activities.

Cheers.

**Comment by hmitsch** [comment] 2017-09-07 12:42
Hi @nukeador, 

this is the current ReMo Dashboard:
<img width="1454" alt="image" src="https://user-images.githubusercontent.com/869692/30163741-5dee91b6-93da-11e7-85db-445f0d093381.png">

Would you agree that the _Categories_ are good enough for the moment. This means we would not add _Project_ Grouping to it for the moment.

Agreed?

Best regards,
   Henrik

**Comment by nukeador** [comment] 2017-09-07 13:07
I would say I miss some categories there, I think groping is also important to be implemented here to be able to cross track activities

https://docs.google.com/spreadsheets/d/1xFrt9JZkZ6m8peasYaRfPO5kC1JDo-vDJJuYfMwcGqM/edit#gid=1022022552

**Comment by hmitsch** [comment] 2019-03-21 12:47
Closing issue.

**Closed by hmitsch** 2019-03-21 12:47 UTC
Labels: Communities and contributors research, June 5
