### ISSUE TITLE
Bugzilla project grouping or index incomplete

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-metrics-org#158] opened 2018-02-13 10:48 UTC
Hello,

Checking the project groping for bugzilla, there are 150 components under "Localization"

https://docs.google.com/spreadsheets/d/1xFrt9JZkZ6m8peasYaRfPO5kC1JDo-vDJJuYfMwcGqM/edit#gid=537261496

But checking on the dashboard, only 6 issues in the last year:

https://analytics.mozilla.community/goto/fb4d80fed5323d015f74596d6cbe009f

![imagen](https://user-images.githubusercontent.com/531906/36146070-9fdc7df8-10b3-11e8-84f0-608cf2a2bb10.png)

I suspect there is an incoherency somewhere. Doing a bugzilla search for bugs in the last year under "Mozilla Localizations" I see at least 600 bugs:

https://bugzilla.mozilla.org/buglist.cgi?chfield=%5BBug%20creation%5D&chfieldfrom=2017-02-01&chfieldto=Now&product=Mozilla%20Localizations&query_format=advanced&order=priority%2Cbug_severity&limit=0

![imagen](https://user-images.githubusercontent.com/531906/36146100-c6ea79c2-10b3-11e8-9ea2-82b9f65132bc.png)

**Comment by zhquan** [comment] 2018-02-13 12:24
Hi @nukeador 
We are working on it
Best,

**Comment by zhquan** [comment] 2018-02-13 14:28
Hi again

The enrichment phase does not work properly but in our raw index contains all items.
We've opened the issue internally and passed it to our developer team to fix it. We will let you know about the state.

Sorry for the inconvenience.

Best,
Quan

**Comment by zhquan** [comment] 2018-02-14 15:43
Hi @nukeador 

We were searching deeper into the data and our project grouping does not work properly
For example:
If you look at the component "Bulgarian" https://bugzilla.mozilla.org/buglist.cgi?product=Mozilla+Localizations&component=bg+/+Bulgarian it has 207 items, and at the [dashboard](https://analytics.mozilla.community/goto/53e89ce5dc966ca352231952c5fee3c6) (we need to search by the word "Bulgarian" and project "unknown")  it has 242 items, more than 207 items because in another items could content the word "Bulgarian" too.

In the [raw index](https://analytics.mozilla.community/edit/goto/0c20bf126f38d2ce8e3399da1d738bbd) if you look at the field "id" is the same id as bugzilla.mozilla.org

Very important: the **time series is ordered by creation date** and not by "changed" as bugzilla.mozilla.org

![bugzilla](https://user-images.githubusercontent.com/5637233/36212516-6cf802ee-11a4-11e8-9781-dd3fde172ec2.png)
![bugzilla2](https://user-images.githubusercontent.com/5637233/36212522-6f42f6d0-11a4-11e8-8901-03c83086f860.png)

Best,
Quan

**Comment by sanacl** [comment] 2018-03-09 17:21
We owe u an update about this @nukeador Sorry for the lag. :turtle:

**Comment by sanacl** [comment] 2018-03-12 10:03
Our development team is working on this. The bugs are collected but the project categorization is not correctly done.

**Comment by sanacl** [comment] 2018-03-14 09:04
The ETA for the fix applied in production is Wednesday 21st.

**Comment by acs** [comment] 2018-03-14 23:21
The fix is ready at: https://github.com/chaoss/grimoirelab-elk/pull/246

Once it is reviewed and merged into product, it must be deployed in Mozilla instance. And after that, the project field must be refreshed. The above estimation by @sanacl is a right one.

**Comment by acs** [comment] 2018-03-15 11:17
> Once it is reviewed and merged into product, it must be deployed in Mozilla instance. And after that, the project field must be refreshed. The above estimation by @sanacl is a right one.

The PR has been included in the product. In the next release, 18.03-02 it will be included and once it is deployed, we can fix the problem refreshing the projects in bugzilla enriched index.

**Comment by sanacl** [comment] 2018-03-22 07:53
We've had some issues with the release 18.03-02 and the one is production is still 18.03-01, as soon as a new release fixing the issue is published it will be deployed. The ETA for this is Wednesday 29th. Sorry for this.

:turtle:

**Comment by sanacl** [comment] 2018-04-04 13:07
Generating new index. We'll evaluate on Friday morning whether the fix worked. This index takes a lot of time to be created.

**Comment by sanacl** [comment] 2018-04-16 14:05
@nukeador This is fixed with the latest release 18.04-02

I've tested it with the 975 items of the project named `Release Engineering` with the component `Mozharness`:

Bugzilla query: https://bugzilla.mozilla.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&component=Mozharness&product=Release%20Engineering&query_format=advanced&resolution=---&resolution=FIXED&resolution=INVALID&resolution=WONTFIX&resolution=DUPLICATE&resolution=WORKSFORME&resolution=INCOMPLETE&resolution=SUPPORT&resolution=EXPIRED&resolution=MOVED&order=bug_status%2Cpriority%2Cassigned_to%2Cbug_id&limit=0

On our dashboard: https://analytics.mozilla.community/goto/59813fa7922c1b4d8ab05d2af8762363

Best,
Luis.

**Closed by sanacl** 2018-04-16 14:05 UTC
